### ISSUE TITLE
multi-tdb path planning error

### ISSUE THREAD

**Issue by amr8004** [PhasesResearchLab/AMMap#13]
When possible, please check the SStoTi64 jupyter notebook to access the error where the path planning ignores the feasibility. It correctly identifies the cross desired start and end of path of SS-V but just goes direct, ignoring feasibility.

**Comment by amkrajewski** [comment]
[like]  Krajewski, Adam M reacted to your message:
________________________________
From: amr8004 ***@***.***>
Sent: Wednesday, September 4, 2024 9:13:17 PM
To: PhasesResearchLab/AMMap ***@***.***>
Cc: Krajewski, Adam M ***@***.***>; Assign ***@***.***>
Subject: [PhasesResearchLab/AMMap] multi-tdb path planning error (Issue #13)


When possible, please check the SStoTi64 jupyter notebook to access the error where the path planning ignores the feasibility. It correctly identifies the cross desired start and end of path of SS-V but just goes direct, ignoring feasibility.

**Comment by amkrajewski** [comment]
You seem to have adjusted the approach to storing phase data from a list of phases lists to a list of dicts with phases lists under `Phases` field. In the functions you wrote, you adjusted that by calculating `[gridPhases[i]['Phases'] for i in range(len(gridPhases))]` (btw, `[gp['Phases'] for gp in gridPhases]` could be simpler) but you did not make adjustments to my functions like `system_graphs`. Since dict keys did not overlap with infeasible phases, their intersection was always empty, returning `True` for feasibility list (`gridFeasible`) and, thus, complete connectivity of edges between adjacent nodes reported in `edges`, i.e. no constraints.

**Comment by amkrajewski** [comment]
@amr8004 I made adjustemnts in https://github.com/PhasesResearchLab/AMMap/commit/53dfd933412b3a1bd712c1f80f174ff167fb5819 - your paths now look happy :)
